apiVersion: apps/v1
kind: Deployment
metadata:
  name: greenchelbot
spec:
  selector:
    matchLabels:
      app: greenchelbot
  replicas: 1
  template:
    metadata:
      labels:
        app: greenchelbot
    spec:
      nodeSelector:
        edge: "true"
      containers:
      - name: greenchelbot
        image: greenchelbot-image-name # USE KUSTOMIZATION
        resources:
          limits:
            cpu: 0m # do not limit
            memory: 128Mi
          requests:
            cpu: 0m # schedule first, think later!
            memory: 0Mi
        volumeMounts:
        - mountPath: /app/secrets
          name: telegram-secrets
      imagePullSecrets:
      - name: docker-registry-cred
      volumes:
      - name: telegram-secrets
        secret:
          secretName: telegram-secret
